name: Secure Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          API_SECRET: ${{ secrets.API_SECRET }}
        run: |
          npm run build
          echo "window.BOT_CONFIG = { 
            botToken: '${{ secrets.BOT_TOKEN }}', 
            adminId: '${{ secrets.ADMIN_ID }}',
            apiSecret: '${{ secrets.API_SECRET }}'
          };" >> public/config.js
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist